### ISSUE TITLE
Gatotech - Q1 2024

### ISSUE THREAD

**Issue by miloskriz** [paseo-network/payouts#10]
Name:  Gatotech Ltd
Contact details (tg/email/element):  `https://t.me/gatotech` / `info@gatotech.uk` / `@gatotech:matrix.org`
Proponent:  `1gatoakSkH4be8KD9Ekj5xCXMdAiGxieg2NfTg41s2UME5J`
Requested DOT: `91.09`
Proactive / Retroactive payment:  Retroactive
Description:  Network Validation Services for Q1 2024.
Evidence: During the period three accounts were linked to Paseo validation services:
- GATOTECH: [5CkHkUKgay1bA77oFWBkaw83fjdX1yQaaBHtWAghTmzxAv1U](https://paseo.subscan.io/account/5CkHkUKgay1bA77oFWBkaw83fjdX1yQaaBHtWAghTmzxAv1U)
-- since genesis 11JAN2024 until 31MAR2024: 20 days out of 31 days possible in January + February + March
-- prorata 22.06 DOT/month * (20/31 + 1 + 1) month = 58.35 DOT
- GATOTECH/UK1: [5Fgato4wJxwZicavjaKQ9oG5e2M1S5wUfy7mMxsw1HTw95ub](https://paseo.subscan.io/account/5Fgato4wJxwZicavjaKQ9oG5e2M1S5wUfy7mMxsw1HTw95ub)
-- since 08MAR2024 until 31MAR2024: 23 days out of 31 days possible in March.
-- prorata 22.06 DOT/month * 23/31 month = 16.37 DOT
- GATOTECH/UK2: [5Ggatomsdkh6ByjPUfrHvEhdGpGNFh8rai1cdzokJz3KvgD1](https://paseo.subscan.io/account/5Ggatomsdkh6ByjPUfrHvEhdGpGNFh8rai1cdzokJz3KvgD1)
-- since 08MAR2024 until 31MAR2024: 23 days out of 31 days possible in March.
-- prorata 22.06 DOT/month * 23/31 month = 16.37 DOT

**Comment by itsbirdo** [comment]
confirmed the wallet address and amount is correct

**Comment by itsbirdo** [comment]
tx proposed to the multisig to sign covering this payment

**Comment by itsbirdo** [comment]
Paid here -> https://polkadot.subscan.io/multisig_extrinsic/20567947-4?call_hash=0x7b1524562d4b440bcfeda6f0b309dc54acf88abb978ec831113334d660783333
