### ISSUE TITLE
Gatotech - Q2 2024

### ISSUE THREAD

**Issue by miloskriz** [paseo-network/payouts#11]
Name:  Gatotech Ltd
Contact details (tg/email/element):  `https://t.me/gatotech` / `info@gatotech.uk` / `@gatotech:matrix.org`
Proponent:  `1gatoakSkH4be8KD9Ekj5xCXMdAiGxieg2NfTg41s2UME5J`
Requested DOT: `132.36`
Proactive / Retroactive payment:  Proactive
Description:  Network Validation Services for Q2 2024.
Evidence: During the period two accounts will be linked to Paseo validation services:
- GATOTECH/UK1: [5Fgato4wJxwZicavjaKQ9oG5e2M1S5wUfy7mMxsw1HTw95ub](https://paseo.subscan.io/account/5Fgato4wJxwZicavjaKQ9oG5e2M1S5wUfy7mMxsw1HTw95ub)
-- since 01APR2024 until 30JUN2024: 3x months.
-- prorata 22.06 DOT/month * 3 month = 66.18 DOT
- GATOTECH/UK2: [5Ggatomsdkh6ByjPUfrHvEhdGpGNFh8rai1cdzokJz3KvgD1](https://paseo.subscan.io/account/5Ggatomsdkh6ByjPUfrHvEhdGpGNFh8rai1cdzokJz3KvgD1)
-- since 01APR2024 until 30JUN2024: 3x months.
-- prorata 22.06 DOT/month * 3 month = 66.18 DOT

**Comment by itsbirdo** [comment]
amount is correct, pending confirmation of address

**Comment by miloskriz** [comment]
Hello Alex, 

proponent account is confirmed for Polkadot (DOT): 1gatoakSkH4be8KD9Ekj5xCXMdAiGxieg2NfTg41s2UME5J.

Hope it is acceptable!

Thanks a lot!

**_Milos_**

**Comment by itsbirdo** [comment]
confirmed the wallet address and amount is correct

**Comment by itsbirdo** [comment]
tx proposed to the multisig to sign covering this payment

**Comment by itsbirdo** [comment]
Paid here -> https://polkadot.subscan.io/multisig_extrinsic/20567947-4?call_hash=0x7b1524562d4b440bcfeda6f0b309dc54acf88abb978ec831113334d660783333
