### ISSUE TITLE
Simply Staking 2024 Q1

### ISSUE THREAD

**Issue by DanielMagro97** [paseo-network/payouts#12]
Name:  Simply Staking
Contact details (tg/email/element):  staking@simplystaking.com
Proponent:  13uwV8CBHjv25W3GACLPzzvTu2v9USc2yCQdhrqPhyM3vx6w
Requested DOT:  $150 / $9.107 (EMA30) = 16.47 DOT
Proactive / Retroactive payment:  Retroactive
Description:  Payout for Simply Staking validator on Paseo Testnet for Q1 2024
Evidence: https://paseo.subscan.io/validator/5GqHPKXy9wCBTZ2LLxkiyuNS9BNCHMV67GtXkvg31i9fgJRN

**Comment by itsbirdo** [comment]
tx proposed to the multisig to sign covering this payment

**Comment by itsbirdo** [comment]
Paid here -> https://polkadot.subscan.io/multisig_extrinsic/20567947-4?call_hash=0x7b1524562d4b440bcfeda6f0b309dc54acf88abb978ec831113334d660783333
