### ISSUE TITLE
RadiumBlock - Q1 2024

### ISSUE THREAD

**Issue by radiumb** [paseo-network/payouts#18]
Name: RadiumBlock
Contact details: [info@radiumblock.com](mailto:info@radiumblock.com)
Proponent: 13GtCixw3EZARj52CVbKLrsAzyc7dmmYhDV6quS5yeVCfnh1
Requested DOT: 2 * 0.5 * $150 = $150 /  $6.799 = 22.06 DOT
Proactive / Retroactive payment: Retroactive
Description: Payout for 2 validators from March 15 to March 31 2024
Evidence:
Paseo Validator 1: https://paseo.subscan.io/validator/5GWKuZt5LX3YaeAjaY3tm5HxmG7cx5kuKxbQvcxhVxxrSsRJ

Paseo Validator 2: https://paseo.subscan.io/validator/5CVMYZfczGFhu3huQcE7RDTNgvNGxBvKczA4Nd6XzRnb6ibC

**Comment by itsbirdo** [comment]
confirmed the amount and wallet address is correct

**Comment by itsbirdo** [comment]
https://polkadot.subscan.io/multisig_extrinsic/21096496-3?call_hash=0xd76ae892d09106c05e1dc6a0f7100e7d620cb882261c036191e7b5a8cb4915c7
