### ISSUE TITLE
Subscan - Q1 2024

### ISSUE THREAD

**Issue by yakio** [paseo-network/payouts#22]
Name: Subscan
Contact details (tg/email/element): @yakio:matrix.org
Proponent: 14RYaXRSqb9rPqMaAVp1UZW2czQ6dMNGMbvukwfifi6m8ZgZ
Requested DOT: 1650.068445 DOT
Proactive / Retroactive payment: Retroactive payment
Description: Subscan explorer Operation and maintenance fee & development fees
Evidence:
Development fee: discounted price $10,000
Operation and maintenance fee: March - $799/mo

2024-06-14 08:55:42 (+UTC), Block #21211311
DOT EMA7 Price ( USD ): 6.544577;
Number of DOT: 1650.068445

https://polkadot.subscan.io/tools/price_converter?value=10799&type=block&from=USD&to=DOT&time=21211311

**Comment by itsbirdo** [comment]
Paid and ready to be claimed -> https://polkadot.subscan.io/extrinsic/21871705-2
