### ISSUE TITLE
Subscan - Q2 & Q3 2024

### ISSUE THREAD

**Issue by yakio** [paseo-network/payouts#23]
Name: Subscan
Contact details (tg/email/element): @yakio:matrix.org
Proponent: 14RYaXRSqb9rPqMaAVp1UZW2czQ6dMNGMbvukwfifi6m8ZgZ
Requested DOT: 732.514874 DOT
Proactive / Retroactive payment: Retroactive payment for Q2, and proactive payment for Q3.
Description: Subscan explorer Operation and maintenance fee
Evidence:
Operation and maintenance fee: $799/mo* 6 = $4794

2024-06-14 08:55:42 (+UTC), Block #21211311
DOT EMA7 Price ( USD ): 6.544577;
Number of DOT: 732.514874

https://polkadot.subscan.io/tools/price_converter?value=4794&type=block&from=USD&to=DOT&time=21211311

**Comment by itsbirdo** [comment]
Paid and ready to be claimed -> https://polkadot.subscan.io/extrinsic/21871705-2
