### ISSUE TITLE
R0GUE IO - 2024#Q3

### ISSUE THREAD

**Issue by al3mart** [paseo-network/payouts#29]
Name:  R0GUE IO
Contact details (tg/email/element):  `go@r0gue.io`
Proponent:  `15pmMM8VbJC6oDNMhxZeoDEaatY6m2mimfpnSfUDtLZdABYS`
Requested DOT:  `5,147.75`
Proactive / Retroactive payment:  Q3
Description: 1 FTE for Paseo Core group.
Evidence: 

Some of the remarkable pieces of work done to this date are:

- Network is up and running giving stable service to its users. At he moment of writing, hosting 16 parachains and maintained by ~82 validators.
- Upgraded the migration guidelines to be more generic, making it suitable for any relay --> Paseo, and including guidelines to keep the history and state of the network. Allowing a flow like: Block #n-1 validated in Rococo, block #n validated in Paseo.
- Continuous runtime upgrades for the relay chain.
- Integrations and fixes for Paseo in polkadot-js/apps repository.
- Nomination management of Paseo validators.
- Support provided to onboarding parachains.
- Support to various ecosystem DevRel teams interfacing with Paseo. This includes activities in hackathons, and documentation generation.

**Comment by itsbirdo** [comment]
Paid and ready to be claimed -> https://polkadot.subscan.io/extrinsic/21871705-2
