### ISSUE TITLE
VALIDORANGE 1Q24

### ISSUE THREAD

**Issue by validorange** [paseo-network/payouts#4]
Name:  Valid Orange
Contact details (tg/email/element):  https://t.me/DougVO, doug@validorange.net, @validorange:matrix.org
Proponent:  1srcFWVcPn2oXEKuddMMTGCLQMDdRqxKKo9qpFTi8PA7NW1
Requested DOT:  (28 + 15 = 43) days / 30 * 22.06 DOT = 31.6193 DOT
Proactive / Retroactive payment:  Retroactive
Description:  Payout for 2 validators, 43 days total
Evidence:

Validator 1 (Initial staking Mar 4, 28 days in quarter):
https://paseo.subscan.io/account/5G9M1Y4GLtEesD97uYjamzuG473WXfCWjfCJzx14nrFpexeV?tab=transfer

Validator 2 (Initial staking Mar 17, 15 days in quarter):
https://paseo.subscan.io/account/5CVS4Vf5atVu3DefmcydzjkEX6njtnqMgtwSqdGBkQXBHWQp

**Comment by itsbirdo** [comment]
Child bounty raised -> https://polkadot.subscan.io/extrinsic/20518311-3
Claimable in 8 days from when this was executed, approx 4/5
