### ISSUE TITLE
Valid Orange 2Q24

### ISSUE THREAD

**Issue by validorange** [paseo-network/payouts#5]
Name: Valid Orange
Contact details (tg/email/element): https://t.me/DougVO, [doug@validorange.net](mailto:doug@validorange.net), @validorange:matrix.org
Proponent: 1srcFWVcPn2oXEKuddMMTGCLQMDdRqxKKo9qpFTi8PA7NW1
Requested DOT: 2 validators * 3 months * 22.06 DOT = 132.36 DOT
Proactive / Retroactive payment: Proactive
Description: Payout for 2 validators @ 3 months each, April thru June 2024
Evidence:

Validator 1:
https://paseo.subscan.io/account/5G9M1Y4GLtEesD97uYjamzuG473WXfCWjfCJzx14nrFpexeV

Validator 2:
https://paseo.subscan.io/account/5CVS4Vf5atVu3DefmcydzjkEX6njtnqMgtwSqdGBkQXBHWQp

**Comment by itsbirdo** [comment]
confirm address is accurate

**Comment by itsbirdo** [comment]
should be 132.38 dot

**Comment by itsbirdo** [comment]
Child bounty raised -> https://polkadot.subscan.io/extrinsic/20518311-3
Claimable in 8 days from when this was executed, approx 4/5
