### ISSUE TITLE
CoinStudio Q4/2024 - additional 5th Paseo validator

### ISSUE THREAD

**Issue by CoinStudioDOT** [paseo-network/payouts#54]
Name: CoinStudio
Contact details (tg/email/element): coinstudio:matrix.org
Proponent: 14EQvBy9h8xGbh2R3ustnkfkF514E7wpmHtg27gDaTLM2str
Requested DOT: **69.8486 DOT**
Proactive / Retroactive payment: Proactive
Description: Payment for added 5th Paseo validator https://github.com/paseo-network/paseo-action-submission/pull/140
Evidence:
Paseo Validator 1: [CoinStudio](https://paseo.subscan.io/account/13jaRkFWMtdp1Ce466mUG2eTVdzaNDURw1iwQWDYee3BfXYf) - period 26/09/2024-12/2024 = 3.166 months * 22.0621 DOT/month = 69.8486 DOT

**Comment by itsbirdo** [comment]
Raised the first part of the TX to cover this payment:
https://polkadot.subscan.io/multisig_extrinsic/23523393-4?call_hash=0xd8815e1e3dfdc91f6d4ddcba8f91d9c8aa6e5ad0246a0c06b95d51eb46dc9481

**Comment by itsbirdo** [comment]
paid and ready to be claimed, closing the issue
