### ISSUE TITLE
R0GUE IO - 2024#Q4

### ISSUE THREAD

**Issue by al3mart** [paseo-network/payouts#58]
Name: R0GUE IO
Contact details (email): go@r0gue.io
Proponent: `15pmMM8VbJC6oDNMhxZeoDEaatY6m2mimfpnSfUDtLZdABYS`
Requested DOT: `5,147.75`
Proactive payment: Q4
Description: 1 FTE for Paseo Core group.
Evidence:
- Network is up and running giving stable service to its users. At the moment of writing, hosting 35 parachains and maintained by 115 validators.
- New system chain: People chain.
- New system chain: Bridge Hub.
- New system chain: Coretime Chain.
- Continuous runtime upgrades for the relay chain and system chain.
- Migration of identities relaychain -> People Chain.
- Migration from slot based scheduling to coretime based scheduling.
- Updating polkadot-js/apps as necessary.
- Support for teams migrating from Rococo to Paseo.
- Support integrating coretime secondary markets.

**Comment by itsbirdo** [comment]
To be paid out in https://polkadot.subscan.io/multisig_extrinsic/23307629-3?call_hash=0x2646abf7047ff0a1b706788261b7f9b4c917d1056579633be03e9ba9c3b457ed

**Comment by itsbirdo** [comment]
Now claimable
https://polkadot.subscan.io/extrinsic/23377562-3
