### ISSUE TITLE
R0GUE - 2024#Q1

### ISSUE THREAD

**Issue by pascore** [paseo-network/payouts#8]
Name:  R0GUE
Contact details (tg/email/element):  paseo.core@skiff.com
Proponent:  `1eAL59EPokQFG4putYKwBjygGu3ewoHtyK3BSrgCMhM9ijf`
Requested DOT: `5,147.75`
Proactive / Retroactive payment:  Retroactive payment for 2024 Q1
Description:  1 FTE @ Paseo Core Group.

Evidence: Some of the remarkable pieces of work done to this date are:

- Network is up and running giving stable service to its users.
- Created guidelines for migrating parachains from Rococo to Paseo.
- Set initial code and initial launch of the network.
- Upgrade Paseo's runtime to its current version `1001002`.
- Integrations and fixed for Paseo in polkadot-js/apps repository.
- Nomination management of Paseo validators.
- Support provided to onboarding parachains.
- Launch of AssetHub.
- Different PASs have been created, we can highlight:
- 
- - Onboarding validators.
- - Onboarding system collators.
- - Support Model.
- - Indexer Explorer.
- - Support Wiki.
- - Support Repository.
- - Hardware Specs.
- - Onboarding Parachains.

**Comment by itsbirdo** [comment]
To confirm this request is for 5,147.75 DOT
Confirmed this is valid and the wallet address is correct.

**Comment by itsbirdo** [comment]
Paid on tx -> https://polkadot.subscan.io/extrinsic/20366116-3
@pascore 

This will be claimable in 8 days, approx the 24th April
