### ISSUE TITLE
R0GUE - 2024#Q2

### ISSUE THREAD

**Issue by pascore** [paseo-network/payouts#9]
Name:  R0GUE
Contact details (tg/email/element): paseo.core@skiff.com 
Proponent:  `17Mhc2sYRBswwpYiTQp2u1C1DoLQtCs9eDdrAqM1DAHvwee`
Requested DOT: `5,147.75`
Proactive / Retroactive payment:  Proactive payment for 2024 Q2
Description:  1 FTE @ Paseo Core Group.
Evidence:

Some of the planned tasks that the team will work on involve but are not restricted to:

- Runtime upgrade 100200 and all new runtimes to upgrade according to the Polkadot Fellowship release.
- Onboard Bridgehub.
- Onboard additional parachains.
- Provide support to onboarding parachain.
- Resources guiding teams to a successful onboarding and clear use of Paseo.
- Onboard more validators.
- Manage Nominations of validators.

**Comment by itsbirdo** [comment]
confirmed this is valid and the wallet address is correct. 
Total DOT payout should be 5,147.75

**Comment by itsbirdo** [comment]
Child bounty raised -> https://polkadot.subscan.io/extrinsic/20368271-3
Claimable in 8 days
